### ISSUE TITLE
Implement longest cycle finding algorithm

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/circle-of-suck#2]
Find and implement an algorithm that finds the longest cycle in a graph. Needs to take inputs of the form `[(u, v), ...]`, where `(u, v)` represents a pair of teams where `u` lost to `v`, and returns a list of the form `[[a, b, c, ...], ...]`, where each inner list is a cycle where each team loses to the next team (e.g. `a` lost to `b`, `b` lost to `c`, ... and `z` lost to `a`)

Implement algorithm in `base.utils`

**Comment by allanwlevy** [comment]
Can we have the inputs as a dictionary like this: {Cal:[Utah, Oregon]}

**Comment by brandonchinn178** [comment]
sure
