### ISSUE TITLE
Arrow heads disappearing?

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/circle-of-suck#28]

**Comment by allanwlevy** [comment]
whoops, my bad

**Comment by brandonchinn178** [comment]
Notes:
- only faded arrow heads disappear (when hovering over an arrow, that arrow's head is still showing, everything else disappears)
- hiding and reshowing the full graph (via Element panel) shows the arrow heads
- ideas
  - make marker different id?
  - make different marker for faded arrow head?
