### ISSUE TITLE
Logos missing on mobile?

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/circle-of-suck#30]
Some of the logos dont seem to render on mobile?

**Comment by allanwlevy** [comment]
All the logos seem to render for me on my Samsung Galaxy S7, but I'm not seeing the styling on the conference selector box.

I also know that Niket can't see logos on his macbook. Maybe this is an apple thing rather than a mobile thing?

**Comment by thomashzhang** [comment]
I believe it's because the image sizes are to big. We might have to go through each image and either find a smaller one or make each of them smaller.

**Comment by brandonchinn178** [comment]
Conference selector box isn't styled on mobile, cuz Chosen doesn't render on mobile (by design). I don't think the selector is an issue.

My Macbook renders fine. It could be the image thing. Someone try that?
