### ISSUE TITLE
Make management command to scrape API

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/circle-of-suck#5]
Blocked by #7 

Make a new [management command](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/) (something like `python manage.py updatecycle`) that accesses the API and creates new games for new data

**Comment by brandonchinn178** [comment]
Use API endpoint `http://api.sportradar.us/ncaafb-t1/2016/REG/schedule.json?api_key=<API_KEY>` and look for items with status `closed`

**Comment by allanwlevy** [comment]
Also adding an optional parameter for the command to choose a timeframe (e.g. 2013-2015) to gather from
